# Generated by Django 5.2.6 on 2025-09-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(db_index=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('role', models.CharField(choices=[('support', 'Тех. поддержка'), ('owner', 'Владелец'), ('admin', 'Администратор'), ('user', 'Пользователь')], default='user', max_length=15)),
                ('language_code', models.CharField(blank=True, choices=[('ru', 'Русский'), ('en', 'Английский')], max_length=2, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-date_joined'],
            },
        ),
    ]
